package:
  name: nextflow
  version: '0.18.3'

build:
  number: 0
  skip: True # [osx]

source:
  fn: nextflow
  url: https://github.com/nextflow-io/nextflow/releases/download/v0.18.3/nextflow

requirements:
  run:
    - java-jdk

test:
  commands:
  - nextflow -h

about:
  home: "https://github.com/nextflow-io/nextflow"
  license: "GPLv3+"
  summary: "A DSL for data-driven computational pipelines http://nextflow.io"
